# For more information visit https://pre-commit.com/
# Install pre-commit hooks by calling:
# pre-commit install
# Run pre-commit hooks by calling:
# pre-commit run [-a]

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-json
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: check-toml
    - id: name-tests-test

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      args: ["--ignore=E127,E501,F541"]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
    - id: pyupgrade

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.0.1
  hooks:
    - id: mypy
      additional_dependencies: ['types-requests']

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black-jupyter

exclude: (?x)^(
            userauth/picmodel/.*|
          )$
